# Generated by Django 4.1.7 on 2023-06-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_covid_prediction_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covidd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cough', models.IntegerField()),
                ('fever', models.IntegerField()),
                ('sore_throat', models.IntegerField()),
                ('shortness_of_breath', models.IntegerField()),
                ('head_ache', models.IntegerField()),
                ('classification', models.IntegerField()),
            ],
        ),
    ]
