# Generated by Django 4.1.7 on 2023-06-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_covidd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Covidd',
            new_name='CovidPredict',
        ),
    ]
